# Generated by Django 5.2.3 on 2025-06-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customersuggestion',
            name='allergens_to_avoid',
        ),
        migrations.RemoveField(
            model_name='customersuggestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='available',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AddField(
            model_name='cart',
            name='flavor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ice_cream_app.flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream_app.allergen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CustomerSuggestion',
        ),
    ]
